---
bungeecord:
  restart: always
  ports:
    - "0.0.0.0:25577:25577"
  links:
    - spigot:spigot

spigot:
  environment:
    - MINECRAFT_VERSION=1.8.8
    - DEFAULT_OP=dinnerbone
    - MINECRAFT_EULA=true
  restart: always
  links:
    - spigot_db:spigot_db

spigot_db:
  environment:
    - MYSQL_ROOT_PASSWORD=spigot
    - MYSQL_DATABASE=spigot
    - MYSQL_USER=spigot
    - MYSQL_PASSWORD=spigot
  restart: always
